[2024-12-16T03:05:01.792+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-16T03:04:59.297556+00:00 [queued]>
[2024-12-16T03:05:01.803+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_library_imports.test_imports manual__2024-12-16T03:04:59.297556+00:00 [queued]>
[2024-12-16T03:05:01.803+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-16T03:05:01.820+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): test_imports> on 2024-12-16 03:04:59.297556+00:00
[2024-12-16T03:05:01.828+0000] {standard_task_runner.py:60} INFO - Started process 4978 to run task
[2024-12-16T03:05:01.833+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_library_imports', 'test_imports', 'manual__2024-12-16T03:04:59.297556+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmp2e0sfri7']
[2024-12-16T03:05:01.835+0000] {standard_task_runner.py:88} INFO - Job 56: Subtask test_imports
[2024-12-16T03:05:01.901+0000] {task_command.py:423} INFO - Running <TaskInstance: test_library_imports.test_imports manual__2024-12-16T03:04:59.297556+00:00 [running]> on host 5324727f1801
[2024-12-16T03:05:02.007+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_library_imports' AIRFLOW_CTX_TASK_ID='test_imports' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T03:04:59.297556+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T03:04:59.297556+00:00'
[2024-12-16T03:05:02.010+0000] {dag1.py:10} INFO - Pandas version: 2.0.3. 
 Pandas imported successfully
[2024-12-16T03:05:02.021+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-12-16T03:05:02.194+0000] {dag1.py:24} ERROR - Error during imports or MySQL connection: (1045, "Access denied for user 'root'@'bras-base-toroon0964w-grc-23-174-91-211-97.dsl.bell.ca' (using password: YES)")
[2024-12-16T03:05:02.195+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-16T03:05:02.203+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=test_library_imports, task_id=test_imports, execution_date=20241216T030459, start_date=20241216T030501, end_date=20241216T030502
[2024-12-16T03:05:02.245+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-16T03:05:02.262+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
